version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing Terraform...
      - wget https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip
      - unzip terraform_1.7.5_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform -version
  pre_build:
    commands:
      - echo Initializing Terraform...
      - terraform init -input=false
      # - aws sts get-caller-identity # Optional debug
  build:
    commands:
      - echo Running Terraform Plan...
      - terraform plan -out=tfplan -input=false
  post_build:
    commands:
      - echo Applying Terraform...
      - terraform apply -auto-approve -input=false tfplan

artifacts:
  files:
    - '**/*'
